FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --production --silent

# Copy source files and build the app
COPY . .
RUN yarn build

# Production stage
FROM node:22-alpine

WORKDIR /app

# Copy built files from builder stage
COPY --from=builder /app/dist ./dist
COPY ./certs /app/certs 
COPY ./certs /app/ssl

# Install only production dependencies
COPY package.json yarn.lock ./
RUN yarn install --production --silent

# Expose port and start the app
EXPOSE 5173

CMD yarn preview --host --port 5173 
